slapdamage = 15
bantime = 0
commandprefix = "!"
rconclient = "console"
modname = "mmod"

global_admin_table = {}
global_ban_table = {}
global_level_table = {}

-- command flags are the same as etpub shrubbot flags
commandflags = {}
commandflags["test"] = "z"
commandflags["admintest"] = "a"
commandflags["ban"] = "b"
commandflags["botplayers"] = "o"
commandflags["date"] = "C"
commandflags["gib"] = "g"
commandflags["help"] = "h"
commandflags["kick"] = "k"
commandflags["listplayers"] = "i"
commandflags["nextmap"] = "n"
commandflags["putteam"] = "p"
commandflags["rename"] = "N"
commandflags["setlevel"] = "s"
commandflags["showbans"] = "B"
commandflags["slap"] = "A"
commandflags["spec999"] = "P"
commandflags["stats"] = "t"
commandflags["swap"] = "w"
commandflags["time"] = "C"
commandflags["timelimit"] = "T"
commandflags["warn"] = "R"

commandhelp = {}
commandhelp["test"] = "^3usage: ^7!test \n^3function: ^7test stuff"
commandhelp["admintest"] = "^3usage: ^7!admintest or !admintest [name|slot] \n^3function: ^7prints out player's current mmod admin level in global chat. When the NAME or SLOT are added and the user has the right mmod permission, the level of another player will be shown"
commandhelp["ban"] = "^3usage: ^7!ban [name|slot] [reason] \n^3function: ^7bans the player and gives them a reason"
commandhelp["botplayers"] = "^3usage: ^7!botplayers [number of bots] \n^3function: ^7changes value of omnibots maxbots"
commandhelp["date"] = "^3usage: ^7!date \n^3function: ^7prints out local date of the server"
commandhelp["gib"] = "^3usage: ^7!gib [name|slot] [reason] \n^3function: ^7kills and gibs the player"
commandhelp["help"] = "^3usage: ^7!help or !help [command] \n^3function: ^7list commands or show help for a command"
commandhelp["kick"] = "^3usage: ^7!kick [name|slot] [reason] \n^3function: ^7kicks the player and gives them a reason"
commandhelp["listplayers"] = "^3usage: ^7!listplayers \n^3function: ^7display a list of players"
commandhelp["nextmap"] = "^3usage: ^7!nextmap \n^3function: ^7loads next map in rotation"
commandhelp["putteam"] = "^3usage: ^7!putteam [name|slot] [b|r|s] \n^3function: ^7move player to another team"
commandhelp["rename"] = "^3usage: ^7!rename [name|slot] [new name] \n^3function: ^7renames a player to a new name"
commandhelp["setlevel"] = "^3usage: ^7!setlevel [name|slot] [level] \n^3function: ^7sets player with admin level"
commandhelp["showbans"] = "^3usage: ^7!showbans \n^3function: ^7show a list of banned players"
commandhelp["slap"] = "^3usage: ^7!slap [name|slot] [reason] \n^3function: ^7slaps player and gives them " .. slapdamage .."hp in damage"
commandhelp["spec999"] = "^3usage: ^7!spec999 \n^3function: ^7moves all players with ping of 999 to the spectators team"
commandhelp["stats"] = "^3usage: ^7!stats or !stats [name|slot]\n^3function: ^7player stats"
commandhelp["swap"] = "^3usage: ^7!swap \n^3function: ^7swaps the players to the opposite team"
commandhelp["time"] = "^3usage: ^7!time \n^3function: ^7prints out local time of the server"
commandhelp["timelimit"] = "^3usage: ^7!timelimit [minutes] \n^3function: ^7change timelimit of current map"
commandhelp["warn"] = "^3usage: ^7!warn [name|slot] [reason] \n^3function: ^7gives a player a warning"
